const monkeyIslandQuotes = [
  "That's the most ridiculous name I’ve ever heard!",
  "The trail ends here.",
  "I want to be a pirate!",
  "Er... I'm over this way.",
  "Bye, now. I'm off to seek my fortune.",
  "Where can I find the Governor?",
  "What's so scary about this LeChuck guy?",
  "What happened to your eye?",
  "Excuse me, but I'm looking for the dart board.",
  "Where can I get a drink?",
  "Nice hat.",
  "Geeze, what an obvious sales pitch.",
  "Nice talking to you.",
  "Woof",
  "I want to be a fireman.",
  "I mean to kill you all!",
  "I can hold my breath for ten minutes!",
  "Should I have a map or something?",
  "You're a bunch of foul-smelling, grog-swilling pigs!",
  "What's in that grog stuff, anyway?",
  "Tell me more about mastering the sword.",
  "Tell me more about mastering the art of thievery.",
  "Tell me more about treasure hunting.",
  "I'll just be running along now.",
  "No thanks. I don't have enough money.",
  "Hey, nice rat!",
  "Yes, I love rats!",
  "Do you guys know the sneaky-looking man on the opposite corner?",
  "Say, are you guys pirates?",
  "I'm really interested in this pirating thing.",
  "Maybe no one will miss just this one thing.",
  "Half the people I know are named Guybrush.", 
  "I hate surprises.",
  "Hello? Anybody in here? HELLO???",
  "Bad things happen to people who sneak up on other people.",
  "Boy, I feel much better knowing there's an officer of the law",
  "I could really use a breath mint.",
  "(gives money)",
  "I think I'd just like to browse.",
  "Who are you?",
  "Can I get you anything?",
  "So, how's the food in there?",
  "Sheriff Shinetop sure is a jerk, isn't he?",
  "How much will you pay me?",
  "Of course I have a helmet. What sort of idiot do you take me for?",
  "(Picks the sword and the shovel)",
  "I'd like some rat repellent, please.",
  "Look behind you! A mouse!",
  "Stand aside, troll, I'm a mighty pirate.",
  "I can out-insult anybody, you brainless clay doppelganger!",
  "Captain Smirk's Big Body Pirate Gym",
  "Uh... ...maybe I'll just leave instead.",
  "Do you know where the Sword Master lives?",
  "Can we step inside? It's a little chilly out here.",
  "Could you train me to be better than the Sword Master?",
  "I do so have what it takes!",
  "All I have is this dead chicken.",
  "You fight like a cow.",
  "Nice night we're having, isn't it?",
  "How do you guys talk so funny?",
  "Prepare to die!",
  "I better just stay back here and eavesdrop.",
  "Hi, I'm selling these fine leather jackets.",
  "Are you some kind of a castaway?",
  "Who are you talking to?",
  "(looks at you) Um... sure.",
  "Boy, it sure is HOT here.",
  "What happened to your pants?",
  "How did you get stranded here?",
  "How come you didn't just go with the chimps?",
  "Excuse me, I've got pressing business to attend to.",
  "AAA!!!",
  "Whoops...",
  "I would have knocked, but I couldn't find a door.",
  "There's a message in it! It's a memo... 'PRIVATE PROPERTY'",
  "Excuse me, I've got pressing business to attend to.",
  "Hi! Seen any big, ugly, scary, see-through pirates around here?",
  "I think I'm going nuts.",
  "You're cannibals?!",
  "Look behind you! A three-headed monkey!",
  "I doubt anyone will miss this piece of junk.",
  "Don't eat me! I'm a mighty pirate!",
  "Money. I want money.",
  "I need a ship.",
  "I'm looking for somebody.",
  "I'm looking for 30 dead guys and one woman.",
  "What happened? Health department shut you down?",
  "Why are you guys talking in pig Latin?",
  "--ahem--",
  "I had a feeling that in hell there would be mushrooms.",
  "Hello, head.",
  "May I please have that necklace?",
  "I don't want to have to hurt you...",
  "What're you going to do? Bite me?",
  "This feels weird.",
  "Yikes! I hate rats!",
  "Oh good, more inventory.",
  "I'll just grab this old root and be on my way.",
  "I did it! I got the root!",
  "I'd love to have you stuffed. I'd make a fortune.",
  "What happened to the ship?",
  "...Hey... How did you get in here without a head?",
  "If you have a ship, why are you waiting to be rescued?",
  "Yikes!",
  "I'm selling this fine mouthwash.",
  "I must have left it in my other pants. Bye now.",
  "My chains are at the cleaners being degreased.",
  "How did you manage to escape?",
  "If you're here, then who's that in the dress?",
  "What?",
  "Oh, I'll get it!",
  "...oops...",
  "Well, I can't believe your stupidity.",
  "Well, I can't believe your enormity.",
  "Well, I can't believe your atrocity.",
  "Well, I can't believe your alacrity.",
  "...Er... ...say, now... ...let's not be hasty...",
  "Yikes! Don't sneak up on me like that!",
  "He sure looks nice exploding against the night sky.",
  "I wish me crew could have seen this...",
  "At least I learned something from all of this... How to deal with frustation, disappointment, and irritating cynicism",
  "Yikes!"
];

function quote(msg) {
  const random = Math.floor(Math.random() * monkeyIslandQuotes.length);
  if (random === 0) {
    msg.reply(monkeyIslandQuotes[random])
  } else {
    msg.channel.send(monkeyIslandQuotes[random])
  }
}

function greetings(member) {
  const channel = member.guild.channels.cache.find(ch => ch.name === 'member-log');
  if (!channel) return;
  channel.send(`Welcome to the server, ${member}`);
}

module.exports = { 
  quote,
  greetings
};
  